name = "piercing-productivity-suite-gateway-worker"
main = "src/index.ts"
compatibility_date = "2022-10-05"

[vars]
APP_BASE_URL = "https://piercing-productivity-suite.pages.dev"

[env.local.vars]
APP_BASE_URL = "http://localhost:8585"

[[services]]
binding = "login-fragment"
service = "piercing-productivity-suite-login-fragment"

[[env.local.services]]
binding = "login-fragment"
service = "piercing-productivity-suite-login-fragment-local"

[[services]]
binding = "todo-lists-fragment"
service = "piercing-productivity-suite-todo-lists-fragment"

[[env.local.services]]
binding = "todo-lists-fragment"
service = "piercing-productivity-suite-todo-lists-fragment-local"