name = "cloud-gallery-gallery"
# `web-experiments` account (replace this with your own account id)
account_id = "8ed4d03ac99f77561d0e8c9cbcc76cb6"

compatibility_date = "2022-07-25"
compatibility_flags = ["streams_enable_constructors"]
# The SSR code is generated in the `server` directory.
main = "server/entry.ssr.js"
# The client code is generated in the `dist` directory.
# We use the `assets` config to supply these static files as needed.
[assets]
bucket = "./dist"
browser_TTL = 31536000 # cache assets for a year.
[build]
# Build the SSR code that will run in the Worker.
command = "npm run build"
# Rebuild when the helper library changes
watch_dir = ["src", "../helpers/src"]
