name = "productivity-suite-todos-fragment"
compatibility_date = "2022-10-05"
compatibility_flags = ["streams_enable_constructors"]
main = "dist/server/index.js"

[build]
    command = "npm run build"
    watch_dir = ["src", "../../shared/src"]

[site]
    bucket = "dist/client"

[build.env.local]
   command = "npm run build-local"
