name = "productivity-suite-todos-fragment"
compatibility_date = "2022-10-05"
compatibility_flags = ["streams_enable_constructors"]
main = "dist/server/index.js"

# `web-experiments` account (replace this with your own account id)
account_id = "8ed4d03ac99f77561d0e8c9cbcc76cb6"

[build]
    command = "npm run build"
    watch_dir = ["src", "../../shared/src"]

[site]
    bucket = "dist/client"
