name = "productivity-suite-login-fragment"
compatibility_date = "2022-10-05"
main = "server/entry.ssr.js"
assets = "./dist"

# `web-experiments` account (replace this with your own account id)
account_id = "8ed4d03ac99f77561d0e8c9cbcc76cb6"

[build]
command = "npm run build"
watch_dir = ["src", "../../shared/src"]
