name = "productivity-suite-login-fragment"
compatibility_date = "2022-10-05"
main = "server/entry.ssr.js"
assets = "./dist"

[build]
command = "npm run build"
watch_dir = ["src", "../../shared/src"]

[build.env.local]
command = "npm run build-local"
