name = "productivity-suite-todo-lists-fragment"
compatibility_date = "2022-10-05"
main = "server/entry.ssr.js"
assets = "./dist"

[build]
watch_dir = ["src", "../../shared/src"]
command = "npm run build"
